---
- name: First playbook
  hosts: deployment_target
  become: true
  tasks:
    - name: Downloading Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: S Apache
      ansible.builtin.service:
        name: apache2
        state: started
    - name: Description
        # Comment
      ansible.builtin.apt:
        allow_downgrade: true
        allow_unauthenticated: true
        autoclean: true
        autoremove: true
        force: true
        install_recommends: false
        name:
          - element
        update_cache: false
