---
- name: Deploy project with DockerFile
  hosts: deployment_target
  become: true
  vars:
    repo_url: "https://github.com/frobe11/bastard-pixel-battle-server"
    project_dir: "/home/{{ ansible_user }}/projects/bastard-pixel-battle-server"
    docker_image_name: "bpb-server"
    container_name: "bpb-server-container"
    container_port: "8080"

  tasks:
    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        update: true
      tags:
        - build

    - name: Build Docker-image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        build:
          path: "{{ project_dir }}"
        source: build
      tags:
        - build

    - name: Clean up old container, if it exist ofc
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      tags:
        - clean up

    - name: Run new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}"
        ports:
          - "{{ container_port }}:8080"
        env:
          PORT: 8080
        detach: true
      tags:
        - deploy
