---
- name: Deploy project with DockerFile
  hosts: deployment-target
  become: true
  vars:
    repo_url: "https://github.com/frobe11/bastard-pixel-battle-server.git"
    project_dir: "/home/{{ ansible_user }}/deployment/bastard-pixel-battle-server"
    docker_image_name: "bpb-server"
    container_name: "bpb-server-container"
    container_port: "9124"
    dockerfile: DockerFile

  tasks:
    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        update: true
      tags:
        - build

    - name: Build Docker-image
      community.docker.docker_image_build:
        name: "{{ docker_image_name }}"
        path: "{{ project_dir }}"
        dockerfile: "{{ dockerfile }}"
      tags:
        - build

    - name: Clean up old container, if it exist ofc
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      tags:
        - clean_up

    - name: Run new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ container_port }}:8080"
        env:
          PORT: "8080"
        detach: true
      tags:
        - deploy
